manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: zmk-locales
      url-base: https://github.com/joelspadin
    - name: mrtnRitter
      url-base: https://github.com/mrtnRitter
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0
      import: app/west.yml
    - name: zmk-locales
      remote: zmk-locales
      revision: main
    - name: nice-view-c
      remote: mrtnRitter
      revision: main
  self:
    path: config
